### ISSUE TITLE
Does querying all components still provide code-splitting benefits, even if unused?

### ISSUE THREAD

**Issue by ghost** [pristas-peter/gatsby-plugin-graphql-component#1]
Firstly great plugin!!

**Question:**
If I use a StaticQuery to query all my components in wrapper component file, will I still see the code-splitting/performance benefits even if I only return a select component?

**Example:**
To give an example, this is what I'm working with... 

```
import React from "react";
import { graphql, useStaticQuery } from "gatsby";

const AllComponents = ({ layoutType, componentData }) => {

  const componentType = componentData.fieldGroupName;
  const {Banner} = useStaticQuery(graphql`query ComponentQuery {Banner}`);

  const Default = () => <div>In AllComponents the mapping of this component is missing: {componentType}</div>;

  /**
   * Mapping the fieldGroupName(s) to our components
   */
  const components = {
    [`${layoutType}_Components_Banner`]: Banner,
    page_default: Default
  };

  /**
   * If layout type is not existing in our mapping, it shows our Default instead.
   */
  const ComponentTag = components[componentType] ? components[componentType] : components['page_default'];

  return (
    <ComponentTag {...componentData} />
  )
};

export default AllComponents;
```

I am just using the Banner component as a rudimentary example. The idea is I would be querying all my components to dynamically render the appropriate one based on the componentType. AllComponents is essentially a wrapper component for this purpose, and is implemented in a parent layout elsewhere like this...

```
import React from "react";
import AllComponents from "../../components/UtilWrappers/AllComponents";

const FullWidth = ({fieldGroupName, components}) => {

  const layoutType = fieldGroupName;

  return (
    <section style={{ position: "relative" }}>
      {
        components.map((component, index) => {
          return <AllComponents key={index} componentData={component} layoutType={layoutType} />
        })
      }
    </section>
  );

};

export default FullWidth;
```

I'm trying to find a work around to importing all potential components into the AllComponents file because of performance implications, and this plugin looked like a great potential option. 

However, I don't know if I am miss using this plugin, and by querying all components in my AllComponents file I'm just recreating the same problem I have by importing all components.

Any advice/guidance is appreciated! And one again, great plugin!

**Comment by pristas-peter** [comment]
If I understand your cause correctly, you should move the all components logic into the resolver and return the appropriate component as the result of query. What i meant is `const componentType = componentData.fieldGroupName;` should be handled by the query itself like 

```graphql
query {
 # ... 
 
 dataWhichProduceComponent {
    fieldGroupName
    Component # <- add the field with the specific component here in the schema
 }
}
```

Does that makes sense for you?

**Comment by ghost** [comment]
Thank you!

I kind of follow you...when you say to move the AllComponent logic into the resolver are you referring to the createResolvers API resolve function?

**Comment by pristas-peter** [comment]
Yes, exactly. 

You should know what components you need in `sourceNodes`, so you register them there, this adds them to webpack build as a new code split, and in `createResolvers` you should know the mapping of which source data maps to which component, so you return the proper component there.

**Comment by ghost** [comment]
Yup, with you know! That makes sense. Thanks for the clarification. Appreciate it.
